### PR TITLE
remove "remove bookmarks" part of the signout message

### LINKED ISSUE #2530: Remove “bookmarks will be removed” on logout
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.26.0 (1543766544)
Device: iPhone X (iOS 12.1)
TestFlight: true
</pre>
</details>

### PR DESCRIPTION
**Pull request by romankl**
Right now the logout mentions that the bookmarks are removed during the logout process, but the `sessionManager` just signs out

fixes #2530

### CODE REVIEW

File: Classes/Settings/SettingsViewController.swift [hunk 1]
```diff
@@ -203,7 +203,7 @@ GitHubSessionListener {
 
     private func onSignOut() {
         let title = NSLocalizedString("Are you sure?", comment: "")
-        let message = NSLocalizedString("All of your accounts will be signed out, and their bookmarks will be removed. Do you want to continue?", comment: "")
+        let message = NSLocalizedString("All of your accounts will be signed out. Do you want to continue?", comment: "")
```
Comment (jdisho) [inline Classes/Settings/SettingsViewController.swift]: Suggestion: _You will be signed out from all of your accounts. Do you want to sign out?_ 

The two buttons are `Cancel` and `Sign out` and  imo, the message  _Do you want to sign out?_ reflects the `Sign out` action.

Comment (romankl) [reply Classes/Settings/SettingsViewController.swift]: @jdisho thanks for the help! I've changed it

File: Classes/Settings/SettingsViewController.swift [hunk 2]
```diff
@@ -203,7 +203,7 @@ GitHubSessionListener {
 
     private func onSignOut() {
         let title = NSLocalizedString("Are you sure?", comment: "")
-        let message = NSLocalizedString("All of your accounts will be signed out, and their bookmarks will be removed. Do you want to continue?", comment: "")
+        let message = NSLocalizedString("You will be signed out from all of your accounts. Do you want to sign out?", comment: "")
         let alert = UIAlertController.configured(title: title, message: message, preferredStyle: .alert)
```
Comment (j-f1) [inline Classes/Settings/SettingsViewController.swift]: Should this be an action sheet instead, like the delete-photo action sheet in Photos?

Comment (Huddie) [reply Classes/Settings/SettingsViewController.swift]: 🤔 that does fit the app style and will look better when we add the (sign out, sign out of all,
Cancel) once we are able to do selective sign out

Comment (romankl) [reply Classes/Settings/SettingsViewController.swift]: @Huddie should I prepare this part for an ActionSheet style control?

Comment (Huddie) [reply Classes/Settings/SettingsViewController.swift]: Ya, I think ActionSheet makes sense. Fits the style and works better with the future selective sign-out option.

Comment (romankl) [reply Classes/Settings/SettingsViewController.swift]: @Huddie I've changed it!
image
What do you think? It was just an idea to change the primary action string to `sign out of all`

Comment (Huddie) [reply Classes/Settings/SettingsViewController.swift]: I’d leave it as “Sign out” for now

Comment (romankl) [reply Classes/Settings/SettingsViewController.swift]: @Huddie I've reverted the change
