### PR TITLE
Notification a11y actions

### LINKED ISSUE #1881: Cell actions not accessible with VoiceOver
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.22.0 (1529261281)
Device: iPhone X (iOS 11.4)
TestFlight: true
</pre>
</details>

### PR DESCRIPTION
**Pull request by BasThomas**
Fixes #1881 

The guts of this pull request can be found in 9c8d8c2265557fece7948dad51e360700bbce10c

That was fun :)

notification-cell
notification-actions

### CODE REVIEW

File: Classes/Notifications/NotificationCell.swift [hunk 1]
```diff
@@ -182,6 +182,31 @@ final class NotificationCell: SelectableCell {
         watchButton.setImage(UIImage(named: "\(watchingImageName)-small")?.withRenderingMode(.alwaysTemplate), for: .normal)
 
         contentView.alpha = model.read ? 0.5 : 1
+
+        let watchAccessibilityAction = UIAccessibilityCustomAction(
+            name: model.watching ?
+                NSLocalizedString("Unwatch notification", comment: "") :
```
Comment (viktorgardart) [inline Classes/Notifications/NotificationCell.swift]: Should maybe create `Constants.Strings` for these two as well? 🙂

Comment (BasThomas) [reply Classes/Notifications/NotificationCell.swift]: We could do that, but held off as they're only used once right now.

**Comment by joe3355** [comment]
- #1890GitHawk Upload by joe3355

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
