### PR TITLE
Dont show menu button if no actions

### LINKED ISSUE #2009: Don’t show action button if there are no available actions
GitHawk Upload by BasThomas

https://github.com/WeTransfer/WeScan/issues/43

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.22.0 (1532907001)
Device: iPhone X (iOS 11.4.1)
TestFlight: true
</pre>
</details>

### PR DESCRIPTION
**Pull request by rnystrom**
Fixes #2009

### CODE REVIEW

File: Classes/Issues/IssueManagingContextController.swift [hunk 1]
```diff
@@ -66,16 +66,7 @@ final class IssueManagingContextController: NSObject, ContextMenuDelegate {
...
-        if resultID == nil {
-            hidden = true
-        } else {
-            switch permissions {
-            case .none: hidden = true
-            case .author, .collaborator: hidden = false
-            }
-        }
-        manageButton.isHidden = hidden
+        manageButton.isHidden = actions.count == 0
```
Comment (BasThomas) [inline Classes/Issues/IssueManagingContextController.swift]: Why didn't you go for `isEmpty` here? 😛

Comment (rnystrom) [reply Classes/Issues/IssueManagingContextController.swift]: Always forget that’s a thing
