### PR TITLE
Reply button on comments

### LINKED ISSUE #1551: Reply button on comments
Far right (opposite reaction button). Tap and prefill text with `@mention` text. Maybe long press to mention _and_ quote?

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.18.0 (1519059961)
Device: iPhone X (iOS 11.2.2)
TestFlight: true
</pre>
</details>

### PR DESCRIPTION
**Pull request by jdisho**
This PR closes  #1551 🎉

Tap and prefill `messageView` with **@mention** text, together with a part of the comment as a quote.

### CODE REVIEW

File: Classes/Issues/Comments/IssueCommentSectionController.swift [hunk 1]
```diff
@@ -10,15 +10,26 @@ import UIKit
 import IGListKit
 import TUSafariActivity
 import GitHubAPI
+import MessageViewController
```
Comment (YuryBogdanov) [inline Classes/Issues/Comments/IssueCommentSectionController.swift]: I don't think `IssueCommentSectionController` should know anything about MessageViewController

Comment (jdisho) [reply Classes/Issues/Comments/IssueCommentSectionController.swift]: That’s correct! Forgot to remove it before pushing 😄
Thanks!!

File: Classes/Issues/Comments/IssueCommentSectionController.swift [hunk 2]
```diff
@@ -11,14 +11,24 @@ import IGListKit
...
-IssueCommentReactionCellDelegate,
-AttributedStringViewDelegate,
-EditCommentViewControllerDelegate,
-IssueCommentDoubleTapDelegate {
+    IssueCommentReactionCellDelegate,
+    AttributedStringViewDelegate,
+    EditCommentViewControllerDelegate,
+    IssueCommentDoubleTapDelegate {
+
+    var issueCommentDelegate: IssueCommentSectionControllerDelegate!
```
Comment (rnystrom) [inline Classes/Issues/Comments/IssueCommentSectionController.swift]: Shouldn't this be:
```swift
private weak var issueCommentDelegate: IssueCommentSectionControllerDelegate?
```

File: Classes/Issues/IssuesViewController.swift [hunk 3]
```diff
@@ -539,4 +544,27 @@ IssueManagingNavSectionControllerDelegate {
...
+    // MARK: IssueCommentSectionControllerDelegate
+
+    func didSelectReply(to sectionController: IssueCommentSectionController, commentModel: IssueCommentModel) {
+        setMessageView(hidden: false, animated: true)
+        messageView.textView.becomeFirstResponder()
+        messageView.text = ">"
+            + getCommentUntilNewLine(from: commentModel.rawMarkdown)
+            + "\n\n"
+            + "@"
+            + commentModel.details.login
```
Comment (rnystrom) [inline Classes/Issues/IssuesViewController.swift]: This string concat is a bit slow to compile. Could we simply do:
```swift
let quote = getCommentUntilNewLine(from: commentModel.rawMarkdown)
messageView.text = ">\(quote)\n\n@\(commentModel.details.login)"
```

File: Classes/Issues/IssuesViewController.swift [hunk 4]
```diff
@@ -14,21 +14,24 @@ import SnapKit
...
+    IssueManagingNavSectionControllerDelegate,
+    IssueCommentSectionControllerDelegate {
 
     private let client: GithubClient
     private let model: IssueDetailsModel
     private let addCommentClient: AddCommentClient
     private let textActionsController = TextActionsController()
     private var bookmarkNavController: BookmarkNavigationController? = nil
     private var autocompleteController: AutocompleteController!
+    private var focusedCommentModel: IssueCommentModel?
```
Comment (rnystrom) [inline Classes/Issues/IssuesViewController.swift]: What's this for? Can we remove?

File: Classes/Issues/IssuesViewController.swift [hunk 5]
```diff
@@ -549,14 +548,10 @@ final class IssuesViewController:
     func didSelectReply(to sectionController: IssueCommentSectionController, commentModel: IssueCommentModel) {
         setMessageView(hidden: false, animated: true)
         messageView.textView.becomeFirstResponder()
-        messageView.text = ">"
-            + getCommentUntilNewLine(from: commentModel.rawMarkdown)
-            + "\n\n"
-            + "@"
-            + commentModel.details.login
+        let quote = getCommentUntilNewLine(from: commentModel.rawMarkdown)
+        messageView.text = ">\(quote)\n\n@\(commentModel.details.login)"
```
Comment (BasThomas) [inline Classes/Issues/IssuesViewController.swift]: What about making this a multiline String literal to keep it a bit more readable?

```swift
let quote = """
>\(quote)
\n\n
@\(commentModel.details.login)
"""
```

Comment (BasThomas) [reply Classes/Issues/IssuesViewController.swift]: Hm, this supports only the first line of a comment? :/

Comment (jdisho) [reply Classes/Issues/IssuesViewController.swift]: Haha I replied to the wrong cell. Check above 😄

File: Classes/Issues/IssuesViewController.swift (hunk 4 above)
Comment (BasThomas) [reply Classes/Issues/IssuesViewController.swift]: You can

```
> first line
>
> second line
```

Right?

Comment (jdisho) [reply Classes/Issues/IssuesViewController.swift]: That's possible. So you think is a better idea to show the full comment? 
I prefer showing the preview, the comment you replaying is on the same view, easily reachable and the user I am replying knows about the context. 

Otherwise too many information on the new comment cell..

Comment (jdisho) [reply Classes/Issues/IssuesViewController.swift]: What I prefer even more, is when you press on the preview, the view is focused on that comment.

**Comment by jdisho** [comment]
Should I do something about this PR @rnystrom? It still has "requested changes" status

**Comment by rnystrom** [comment]
I just haven’t had a chance to revisit, will do soon

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jdisho** [comment]
Conflicts are fixed @rnystrom 😊
