### PR TITLE
Fixes Reaction emoji updates on split view

### LINKED ISSUE #2356: Reaction emoji doesn’t update in split view
If your in split view and set a new default reaction in settings the emoji icon won’t update in the main view (settings). 

This is because the cells only update on viewDidAppear.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

### PR DESCRIPTION
**Pull request by rizwankce**
Closes #2356

Sry! oversight from mysids. This was introduced from my previous PR. 😦

### CODE REVIEW

File: Classes/Settings/DefaultReactionDetailController.swift [hunk 1]
```diff
@@ -18,6 +22,8 @@ class DefaultReactionDetailController: UITableViewController {
     @IBOutlet var heartCell: UITableViewCell!
     @IBOutlet var enabledSwitch: UISwitch!
 
+    var listener: DefaultReactionListener?
```
Comment (rnystrom) [inline Classes/Settings/DefaultReactionDetailController.swift]: `weak` to avoid retain cycle! Also the protocol + var should just use the term "Delegate" b/c this is a 1:1 (not 1:n)

Comment (rizwankce) [reply Classes/Settings/DefaultReactionDetailController.swift]: Done! Thx for pointing out.
